"""Product book for Harbor & Co."""

from __future__ import annotations

from typing import Any

CATEGORIES = [
    ("all", "All"),
    ("home", "Home"),
    ("table", "Table"),
    ("wear", "Wear"),
    ("outdoor", "Outdoor"),
]

PRODUCTS: list[dict[str, Any]] = [
    {
        "id": "linen-throw",
        "name": "Flax linen throw",
        "category": "home",
        "price": 4800,
        "stock": 14,
        "img": "/assets/img/throw.jpg",
        "blurb": "Stonewashed flax. Heavy enough for a monsoon evening.",
        "desc": "Woven in a 140 by 200 centimetre cloth and washed until the hand goes soft. It lives on the sofa or the foot of the bed.",
        "specs": [("Cloth", "European flax linen"), ("Size", "140 × 200 cm"), ("Care", "Cold wash, line dry")],
        "rating": 4.8,
        "reviews": [
            {"name": "R. Kulkarni", "stars": 5, "text": "Weight is honest. No sheen."},
            {"name": "A. Sen", "stars": 5, "text": "Took it to Alibag. Sand brushes off."},
        ],
        "featured": True,
        "new": True,
        "sizes": (),
    },
    {
        "id": "stone-pourer",
        "name": "Bone stoneware pourer",
        "category": "table",
        "price": 2200,
        "stock": 9,
        "img": "/assets/img/pourer.jpg",
        "blurb": "A single pour for water or wine. Matte bone glaze.",
        "desc": "Thrown in a small Pune kiln. The lip is cut thin so it does not dribble. Holds just under a litre.",
        "specs": [("Clay", "Stoneware"), ("Hold", "900 ml"), ("Finish", "Matte bone")],
        "rating": 4.7,
        "reviews": [{"name": "M. Iyer", "stars": 5, "text": "Replaced three glass jugs."}],
        "featured": True,
        "new": False,
        "sizes": (),
    },
    {
        "id": "oak-board",
        "name": "End-grain oak board",
        "category": "table",
        "price": 3600,
        "stock": 6,
        "img": "/assets/img/board.jpg",
        "blurb": "Thick oak with a brass lift. Built to be used, not hung.",
        "desc": "End-grain so knives last. Oil it once a month. The brass tab is there so wet hands can pick it up.",
        "specs": [("Wood", "European oak"), ("Size", "40 × 28 cm"), ("Finish", "Food-grade oil")],
        "rating": 4.9,
        "reviews": [{"name": "S. Patel", "stars": 5, "text": "Heavier than it looks. Good."}],
        "featured": True,
        "new": False,
        "sizes": (),
    },
    {
        "id": "canvas-tote",
        "name": "Harbor canvas tote",
        "category": "outdoor",
        "price": 1800,
        "stock": 22,
        "img": "/assets/img/tote.jpg",
        "blurb": "Undyed canvas. Holds a market run or a wet towel.",
        "desc": "Sixteen-ounce canvas, bar-tacked handles, one interior slip. It darkens with weather and that is the point.",
        "specs": [("Cloth", "16 oz canvas"), ("Volume", "18 L"), ("Origin", "Tiruppur")],
        "rating": 4.6,
        "reviews": [{"name": "N. Mehta", "stars": 4, "text": "Straps sit well on a shoulder."}],
        "featured": False,
        "new": True,
        "sizes": (),
    },
    {
        "id": "wool-overshirt",
        "name": "Olive wool overshirt",
        "category": "wear",
        "price": 8900,
        "stock": 7,
        "img": "/assets/img/overshirt.jpg",
        "blurb": "A jacket you forget you are wearing. Cut easy over a tee.",
        "desc": "Italian wool blend, corozo buttons, two chest pockets. Unlined so it layers. Runs true.",
        "specs": [("Cloth", "Wool blend"), ("Fit", "Easy"), ("Care", "Dry clean")],
        "rating": 4.8,
        "reviews": [{"name": "K. Rao", "stars": 5, "text": "M size over a knit. Right."}],
        "featured": True,
        "new": True,
        "sizes": ("S", "M", "L", "XL"),
    },
    {
        "id": "brass-holder",
        "name": "Turned brass holder",
        "category": "home",
        "price": 1400,
        "stock": 18,
        "img": "/assets/img/brass.jpg",
        "blurb": "Solid brass. It will tarnish. That is the finish.",
        "desc": "Turned from a single rod. Fits a standard taper. Leave it unpolished.",
        "specs": [("Metal", "Solid brass"), ("Height", "11 cm"), ("Fit", "22 mm taper")],
        "rating": 4.5,
        "reviews": [{"name": "P. Shah", "stars": 4, "text": "Heavier than expected."}],
        "featured": False,
        "new": False,
        "sizes": (),
    },
    {
        "id": "bowl-set",
        "name": "Nested clay bowls",
        "category": "table",
        "price": 3200,
        "stock": 8,
        "img": "/assets/img/bowls.jpg",
        "blurb": "Three bowls. Breakfast, rice, and the one you steal for keys.",
        "desc": "A nest of three in bone and clay glazes. Dishwasher if you must. Better by hand.",
        "specs": [("Set", "3 bowls"), ("Largest", "22 cm"), ("Finish", "Satin glaze")],
        "rating": 4.7,
        "reviews": [{"name": "L. Banerjee", "stars": 5, "text": "The small one is the favourite."}],
        "featured": False,
        "new": False,
        "sizes": (),
    },
    {
        "id": "cotton-apron",
        "name": "Workshop cotton apron",
        "category": "wear",
        "price": 2100,
        "stock": 11,
        "img": "/assets/img/apron.jpg",
        "blurb": "Leather neck, long ties, a pocket that actually holds a phone.",
        "desc": "Heavy cotton drill. One size, wrap and tie. The leather strap is replaceable.",
        "specs": [("Cloth", "Cotton drill"), ("Fit", "One size"), ("Pocket", "Split hip")],
        "rating": 4.6,
        "reviews": [{"name": "D. Nair", "stars": 5, "text": "Cooks and clay. Same apron."}],
        "featured": False,
        "new": False,
        "sizes": (),
    },
    {
        "id": "seagrass-basket",
        "name": "Seagrass floor basket",
        "category": "home",
        "price": 2600,
        "stock": 5,
        "img": "/assets/img/basket.jpg",
        "blurb": "Throws, kindling, or the week's paper.",
        "desc": "Hand-coiled seagrass with two loop handles. It will soften. Keep it dry.",
        "specs": [("Fibre", "Seagrass"), ("Height", "42 cm"), ("Origin", "Tamil Nadu")],
        "rating": 4.4,
        "reviews": [{"name": "H. Joshi", "stars": 4, "text": "Bigger than the photo. Good."}],
        "featured": False,
        "new": False,
        "sizes": (),
    },
    {
        "id": "daypack",
        "name": "Waxed canvas daypack",
        "category": "outdoor",
        "price": 6400,
        "stock": 4,
        "img": "/assets/img/pack.jpg",
        "blurb": "A day's walk. Waxed canvas, tan straps, no extra pockets.",
        "desc": "Eighteen litres. Laptop sleeve, one external pocket, brass hardware. The wax will scar.",
        "specs": [("Cloth", "Waxed canvas"), ("Volume", "18 L"), ("Laptop", "13 inch")],
        "rating": 4.9,
        "reviews": [{"name": "V. Kapoor", "stars": 5, "text": "Rain in Lonavala. Dry inside."}],
        "featured": True,
        "new": False,
        "sizes": (),
    },
    {
        "id": "olive-tin",
        "name": "Estate olive oil",
        "category": "table",
        "price": 1600,
        "stock": 30,
        "img": "/assets/img/oil.jpg",
        "blurb": "A single estate. Pepper at the back of the throat.",
        "desc": "Cold pressed, tinned so light cannot get in. Five hundred millilitres. Finish it in six weeks.",
        "specs": [("Volume", "500 ml"), ("Origin", "Puglia"), ("Harvest", "2025")],
        "rating": 4.8,
        "reviews": [{"name": "T. Desai", "stars": 5, "text": "On tomatoes. Nothing else."}],
        "featured": False,
        "new": True,
        "sizes": (),
    },
    {
        "id": "soap-trio",
        "name": "Amber soap trio",
        "category": "home",
        "price": 1900,
        "stock": 0,
        "img": "/assets/img/soap.jpg",
        "blurb": "Three pumps. Cedar, citrus, unscented. Back next week.",
        "desc": "Castile base in amber glass. Sold as a set. Currently waiting on the next pour.",
        "specs": [("Set", "3 × 250 ml"), ("Base", "Castile"), ("Scent", "Cedar / citrus / none")],
        "rating": 4.3,
        "reviews": [{"name": "J. Fernandes", "stars": 4, "text": "When it is back, take two."}],
        "featured": False,
        "new": False,
        "sizes": (),
    },
]


def get(pid: str) -> dict[str, Any] | None:
    for row in PRODUCTS:
        if row["id"] == pid:
            return row
    return None


def related(pid: str, *, n: int = 3) -> list[dict[str, Any]]:
    src = get(pid)
    if not src:
        return PRODUCTS[:n]
    same = [p for p in PRODUCTS if p["category"] == src["category"] and p["id"] != pid]
    rest = [p for p in PRODUCTS if p["id"] != pid and p not in same]
    return (same + rest)[:n]
